name: kuchaindart
description: This library supports kuchain address generation and verification. It enables you to create an offline signature functions of different types of transaction messages. 
version: 0.1.7
author: KY <harrykyguo@gmail.com>
homepage: https://github.com/keybagio/kuchaindart

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  meta: ^1.1.8

  hex: ^0.1.2
  http: ^0.12.0

  # Crypto utils
  bech32: ^0.1.2
  bip32: ^1.0.5
  bip39: ^1.0.3
  pointycastle: ^1.0.2

dev_dependencies:
  effective_dart: ^1.0.0
  test: ^1.9.0
  coverage: ^0.13.3
